app/users/forms.py
from flask_wtf import FlaskForm
from flask_login import current_user
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, ValidationError, Email
from wtforms.fields.html5 import EmailField
from ..models import User

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}


class RegisterForm(FlaskForm):
    username = StringField('Nombre de usuario', validators=[
                           DataRequired("Este Campo es requerido."), Length(4, 40)])
    email = StringField('Email', validators=[DataRequired("Este Campo es requerido."), Email(
        "Este Email no es valido."), Length(min=10, message="El Email como minimo debera tener 10 caracteres.")])
    password = PasswordField('Contraseña', validators=[DataRequired(
        "Este Campo es requerido."), EqualTo('password_conf', "La contraseña ingresada no son iguales")])
    password_conf = PasswordField('Confirma tu contraseña', validators=[DataRequired(
        "Este Campo es requerido."), EqualTo('password', "Por favor intente ingresar nuevamente la contraseña.")])
    submit = SubmitField('Registrarse')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data.strip()).first()
        if user:
            raise ValidationError('Este nombre de usuario ya existe.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Este email es incorrecto.')


class LoginForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired(
        "Por favor vuelva a ingresar su email."), Email('Por favor Ingrese un email Correcto.')])
    password = PasswordField('Contraseña', validators=[DataRequired(
        "Por favor intente inrgesar una contraseña correcta.")])
    remember = BooleanField('Recordarme', default=False)
    submit = SubmitField('Ingresar')

    def validate_username(self, password):
        user = User.query.filter_by(password=password.data.strip()).first()
        if user:
            raise ValidationError(
                'Por favor intenta nuevamente poner tu contraseña.')


class AccountForm(FlaskForm):
    email = StringField('Email', validators=[
                        DataRequired(), Email("Este email es incorrecto.")])
    username = StringField('Nombre de usuario', validators=[
                           DataRequired(), Length(4, 40)])
    name = StringField('Nombre', validators=[Length(0, 60)])
    address = StringField('Dirección', validators=[Length(0, 60)])
    upload = FileField('Imagen para mi perfil', validators=[
                       FileAllowed(ALLOWED_EXTENSIONS)])
    submit = SubmitField('Actualizar')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data.strip()).first()
            if user:
                raise ValidationError('Este nombre de usuario ya existe.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data.strip()).first()
            if user:
                raise ValidationError('Este email es incorrecto.')

app/users/__init__.py
from flask import Blueprint

users = Blueprint('users', __name__)

from .views import *

app/users/views.py
import os
import asyncio
from flask import (
    render_template,
    redirect,
    url_for,
    flash,
    request,
    jsonify,
    make_response,
    session,
    current_app
)
from flask_login import current_user, login_user, logout_user, login_required
from .forms import RegisterForm, LoginForm, AccountForm
from ..decorators import permission_required
from ..utils import save_upload
from ..models import User, db, Permission
from ..mail import send_token_confirmation
from ..main.forms import SendEmailForm
from . import users


@users.before_app_request
def before_request():
    if current_user.is_authenticated:
        if not current_user.confirmed \
                and request.endpoint \
                and request.blueprint != 'users' \
                and request.endpoint != 'static':
            return redirect(url_for('users.uncorfirmed'))


@users.route('/uncorfirmed')
def uncorfirmed():
    if current_user.is_anonymous or current_user.confirmed:
        return redirect(url_for('main.home'))
    return render_template('users/unconfirmed.html', title="Inconfirmado")


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmed_token()
        asyncio.run(send_token_confirmation(user, token))
        flash(f'Te hemos enviado un mensaje de confirmación de cuenta a tu correo.', 'info')
        return redirect(url_for('main.home'))

    return render_template('users/register.jinja', form=form, title='Registrarse')


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.verify_password(form.password.data):
            login_user(user, remember=form.remember.data)
            session['email'] = form.email.data
            return redirect(url_for('main.home'))
        else:
            flash('Por favor vuelva a Ingresar su nombre de usuario y su contraseña correctamente, Gracias.', 'danger')

    return render_template('users/login.html', title='Ingresar', form=form)


@users.route('/logout')
@login_required
def logout():
    if 'username' in session:
        session.pop('username')
    flash('Cerraste tu Sesión', 'warning')
    logout_user()
    return redirect(url_for('.login'))


@users.route('/auth/<slug>', methods=['GET'])
@users.route('/auth/<int:id>', methods=['GET'])
def show(slug=None):
    form_email = SendEmailForm()
    user = User.query.filter_by(slug=slug).first()
    return render_template('users/show.html', title=user.username, user=user, form_email=form_email)


@users.route('/account/<slug>', methods=['POST', 'GET'])
@login_required
def account(slug=None, id=None):
    form = AccountForm()
    if form.validate_on_submit():

        # Traer el path del upload del usuario logueado (o en session)
        image_current_del = os.path.join(
            current_app.root_path, "static\\uploads\\users", current_user.upload)

        if request.files['upload']:

            # Eliminar el upload actual
            if os.path.exists(image_current_del):
                os.remove(image_current_del)

            # Actualizar el nuevo file subido(en este caso hizo un update el cliente)
            img = save_upload(form.upload.data, 'users', 300)

            # Se asigna como nuevo upload al current user
            current_user.upload = img

        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.name = form.name.data
        current_user.address = form.address.data

        # Se guarda lo cambios
        db.session.commit()
        flash('Actualisaste tu cuenta.', 'success')
        return redirect(url_for('users.account', slug=current_user.slug))

    form.username.data = current_user.username
    form.email.data = current_user.email
    form.upload.data = current_user.upload
    form.name.data = current_user.name
    form.address.data = current_user.address

    return render_template('users/edit.html', title=f'{current_user.username}', form=form)


@users.route('/follow/<slug>', methods=['GET'])
@login_required
@permission_required(Permission.FOLLOW)
def follow(slug):
    user = User.query.filter_by(slug=slug).first()
    if current_user.is_authenticated:
        current_user.follow(user)
        return jsonify('following')


@users.route('/unfollow/<slug>', methods=['GET'])
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(slug):
    user = User.query.filter_by(slug=slug).first()
    if current_user.is_authenticated:
        current_user.unfollow(user)
        return jsonify('unfollowing')


@users.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.home'))
    elif current_user.confirm(token):
        flash(
            f'Felicidades {current_user.username} te acabas de unir a nuestra comunidad', 'success')
    else:
        flash('La confirmación de cuenta a expirado', 'info')
    return redirect(url_for('main.home'))


@users.route('/confirm')
@login_required
def resend_cofirmation():
    token = current_user.generate_confirmed_token()
    asyncio.run(send_token_confirmation(current_user, token))
    flash('Se le envio a su correo un mensaje de confimación de cuenta', 'success')
    return redirect(url_for('main.home'))

app/templates/users/edit.html
{% extends 'base.html' %}
{% from "_form_field.html" import form_field %}
{% block contenido %}
<fieldset class="form-group">
  <legend class="border-bottom mb-4 title-account">{{ current_user.username }}</legend>
  {% if current_user.upload %}
    <img class="image-account" src="{{ current_user.upload_path }}" alt="Foto de mi perfil">
  {% endif %}
  <form method="post" class="w-50 media-body" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form_field(form.username, class='form-control') }}
    </div>
    <div class="form-group">
      {{ form_field(form.email, class='form-control') }}
    </div>
    <div class="form-group">
      {{ form_field(form.name, class='form-control') }}
    </div>
    <div class="form-group">
      {{ form_field(form.address, class='form-control') }}
    </div>
    <div class="form-group">
      {{ form_field(form.upload) }}
      <a href="{{ current_user.upload_path }}">Mi Imagen</a>
    </div>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-primary") }}
    </div>

  </form>
</fieldset>

{% endblock contenido %}

app/templates/users/login.html
{% extends 'base.html' %}
{% from "_form_field.html" import form_field %}

{% block contenido %}
<form method="POST" class="container-md m-5" data-remote="true">
  {{ form.hidden_tag() }}
  <fieldset class="form-group">
    <legend class="border-bottom mb-4">{{ title }}</legend>
    {{ form_field(form.email, class="form-control w-50" , placeholder = "Email") }}
    {{ form_field(form.password, class="form-control w-50", placeholder="Contraseña") }}
    <div class="form-group">
      {{ form.remember.label(class="form-check-label") }}
      {{ form.remember(class="form-check-inline") }}
    </div>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-primary") }}
      <a class="ml-4 text-info" href="{{ url_for('users.register') }}">Registrarse</a>
    </div>

  </fieldset>
</form>
{% endblock contenido %}

app/templates/users/register.jinja
{% extends 'base.html' %}
{% from "_form_field.html" import form_field %}

{% block contenido %}
<div class="row">
	<div class="d-table">
		<div class="col col-md-6 col-xl-6 col-lg-6">
			<div class="d-block register-view">
				<img src="{{ url_for('static', filename='uploads/image.jpg') }}" class="register-img"/>
			</div>
		</div>
		<div class="col col-md-6 col-xl-6 col-lg-6">
			<div class="d-block register-view">
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Registrarse</legend>
						<form method="post">
						{{ form.hidden_tag() }}
							{{ form_field(form.username, class="form-control") }}
							{{ form_field(form.email, class="form-control") }}
							{{ form_field(form.password, class="form-control") }}
							{{ form_field(form.password_conf, class="form-control") }}
						<div class="form-group">
							{{ form.submit(class="btn btn-outline-primary") }}
							<a class="ml-4 text-info" href="{{ url_for('users.login') }}">Iniciar Sesión</a>
						</div>
					</form>
				</fieldset>
			</div>
		</div>
	</div>
</div>
{% endblock contenido %}

app/templates/users/show.html
{% extends 'base.html' %}
{% block contenido %}
<div class="container-md">
  <div class="row">
    <div class="col-md-4">
      <div class="card" style="width: 18rem;">
        {% if user.upload %}
        <img src="{{ user.upload_path }}" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ user.username }}</h5>
          {% if user.name %}<p class="card-text">{{ user.name }}</p>{% endif %}
          {% if user.address %}<p class="card-text">{{ user.address }}</p>{% endif %}
          <p class="card-text">{{ user.email }}</p>
          <div class="mx-center">
            <div class="p-1 text-center followers">
              Seguidores <span class="badge badge-light">{{ user.followers.all() | count }}</span>
            </div>
            <br>
            <div class="p-1 text-center followeds">
              Siguiendo <span class="badge badge-light">{{ user.followed.all() | count }}</span>
            </div>
          </div>
        </div>
        {% if current_user.is_authenticated and current_user != user %}
        <div class="card-body">
          {% if not current_user.is_following(user) %}
          <button type="button" id="follow" data-url="{{ url_for('users.follow', slug = user.slug) }}"
                  class="btn-sm btn btn-success">Seguir
          </button>
          {% else %}
          <button type="button" id="unfollow" data-url="{{ url_for('users.unfollow', slug = user.slug) }}"
                  class="btn-sm btn btn-secondary">Dejar de seguir
          </button>
          {% endif %}
        </div>
        {% endif %}
      </div>
    </div>

    <div class="col-md-8">
      <h3 class="text-teal">Post publicados por <b>{{ user.username }}</b></h3>
      {% for post in user.posts %}
      {% if post.status %}
      <fieldset class="shadow container-md col-lg-10 col-sm-4 my-3">
        <legend>
          <h4 class="text-primary"><a href="{{ url_for('posts.post', slug = post.slug) }}">{{post.title}}</a></h4>
        </legend>
        {% if post.upload %}
        <img class="post-img" src="{{ post.upload_path }}" alt="Imagen del Post" style="width: 240px;">
        {% else %}
        {% endif %}
        <p class="text-body">{{ post.content_html | safe | truncate(150)}}</p>
        <p class="text-muted">{{ post.date_register.strftime('%d ,%B %Y') }}</p>
        <b class="my-3 text-secondary">Cometarios: {{ post.comments | count }}</b>
      </fieldset>
      {% elif current_user == post.author and not post.status %}
      <fieldset class="shadow container-md col-lg-10 col-sm-4 post-ban my-3">
        <legend>
          <h4 class="post-title-ban">{{post.title}}</h4>
        </legend>
        <p class="text-break post-ban-body">Este post fue baneado. Comunicate con el Staff <a href=""></a></p>
      </fieldset>
      {% endif %}
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/users/unconfirmed.html
{% extends 'base.html' %}

{% block contenido %}
<h2 class="text-info"> Ups! Aun no se ha auntenticado {{ current_user.username }} !</h2>
<p>Por favor revise su Correo Electronico para que pueda confirmar su Cuenta!</p>
<p>Sí necesita, un nuevo mensaje de confirmación <a href="{{ url_for('users.resend_cofirmation') }}">Click Aquí!</a></p>
{% endblock %}