app/posts/forms.py
import os
from flask import current_app
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
from flask_pagedown.fields import PageDownField
from ..models import Post
from slugify import slugify

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}


class PostCreateForm(FlaskForm):
    title = StringField('Titulo', validators=[DataRequired(), Length(6, 120)])
    pagedown = PageDownField('Contenido', validators=[DataRequired()])
    upload = FileField('Imagen del Post', validators=[
        FileAllowed(ALLOWED_EXTENSIONS)])
    submit = SubmitField('Publicar Post')

    def validate_title(self, title):
        t = title.data.strip()
        post = Post.query.filter_by(title=t).first()
        if post:
            raise ValidationError(
                'Este post con este nombre ya existe, por favor intenta con otro.')

    def validate_slug(self, title):
        slug = slugify(title.data.strip())
        post = Post.query.filter_by(slug=slug).first()
        if post:
            raise ValidationError(
                'Este post con este nombre ya existe, por favor intenta con otro.')


class CommentForm(FlaskForm):
    body = TextAreaField('Mi comentario', validators=[DataRequired()])
    submit = SubmitField('Publicar mi comentario')

app/posts/__init__.py
from flask import Blueprint

posts = Blueprint('posts', __name__)

from . import views

app/posts/views.py
import os
from . import posts
from .forms import PostCreateForm, CommentForm
from flask import (
    render_template,
    redirect,
    url_for,
    request,
    flash,
    current_app
)
from flask_login import current_user, login_required
from ..models import Post, Permission, Comment
from ..decorators import permission_required
from .. import db
from ..utils import save_upload


@posts.route('/post/<slug>', methods=['GET', 'POST', 'PUT'])
def post(slug):
    post = Post.query.filter_by(slug=slug).first()

    form = PostCreateForm()
    if current_user == post.author:
        if form.validate_on_submit():

            # Traer el path del upload Post
            image_current_del = os.path.join(
                current_app.root_path, "static\\uploads\\posts", post.upload)

            if request.files['upload']:

                if os.path.exists(image_current_del):
                    # Eliminar el upload actual
                    os.remove(image_current_del)

                # Actualizar el nuevo file subido.
                img = save_upload(form.upload.data, 'posts', 700)

                # Se asigna como nuevo upload al post
                post.upload = img

            post.title = form.title.data
            post.content = form.pagedown.data
            db.session.commit()
            flash(f'Actualizaste tu post {post.title}', 'success')
            return redirect(url_for('posts.post', slug=post.slug))
        else:
            form.title.data = post.title
            form.pagedown.data = post.content
            form.upload.data = post.upload

    c_form = CommentForm()

    return render_template('posts/show.html', title=f'Post {post.title}', post=post, form=form, c_form=c_form)


@posts.route('/posts/<slug>', methods=['POST'])
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def post_delete(slug):
    post = Post.query.filter_by(slug=slug).first()
    if current_user == post.author:
        db.session.delete(post)
        db.session.commit()
        flash('Usted ah confirmado la eliminación de su post', 'secondary')
    else:
        flash('Usted no tiene permiso para esta acción', 'warning')
    return redirect(url_for('main.home'))


@posts.route('/posts/new', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.WRITE_POST)
def new():
    form = PostCreateForm()
    if current_user.can(Permission.WRITE_POST) and form.validate_on_submit():
        new_post = Post(
            title=form.title.data.strip(),
            content=form.pagedown.data,
            author=current_user._get_current_object(),
        )
        # Pregunstar si existe un archivo en el input(esto desde el request)
        if request.files['upload']:
            # Crear un nuevo upload para el post
            img = save_upload(form.upload.data)

            # Se asigna como nuevo upload al post
            new_post.upload = img

        db.session.add(new_post)
        db.session.commit()
        flash(f'Se creo tu post "{form.title.data}"', 'success')
        return redirect(url_for('main.home'))

    return render_template('posts/new.html', title='Crear Post', Permission=Permission, form=form)


@posts.route('/posts/<slug>/comments', methods=['POST'])
@login_required
@permission_required(Permission.COMMENT)
def comment(slug):
    c_form = CommentForm()
    if current_user.is_authenticated and c_form.validate_on_submit():
        post = Post.query.filter_by(slug=slug).first()
        comment = Comment(body=c_form.body.data, post=post,
                          author=current_user._get_current_object())
        db.session.add(comment)
        db.session.commit()
        flash('Se publico su comentario.', 'success')
        return redirect(url_for('.post', slug=post.slug))


@posts.route('/posts/<slug>/comments/<comment_id>', methods=['DELETE', 'POST'])
@login_required
def comment_delete(slug=None, comment_id=None):
    post = Post.query.filter_by(slug=slug).first()
    comment = Comment.query.filter_by(post=post).first()

    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('.post', slug=post.slug))

app/templates/posts/_comments.html
<div class="ml-4">
  <h4 class="mt-3 text-info">Comentarios</h4>
  {% for comment in post.comments %}
    <div class="my-3 media" id="comments">
      <img src="{{ comment.author.upload_path }}" class="mr-3 comment-img-author" alt="...">
      <div class="media-body text-break">
        <b class="mt-0">{{ comment.author.username }}</b><br>
        {{ comment.body }}
      </div>
    </div>
    {% if current_user == comment.author %}
      <form action="{{ url_for('posts.comment_delete', slug = comment.post.slug, id = comment.id) }}" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="submit" value="Eliminar mi comentario" class="btn-sm btn btn-outline-danger">
      </form>
    {% endif %}
  {% else %}
    <p>Por el momento su post no tiene comentarios.</p>
  {% endfor %}
</div>

app/templates/posts/_form_comment.html
{% from "_form_field.html" import form_field %}
<div class="form-group">
	{{form_field(c_form.body, class="form-control")}}
	{{ c_form.submit(class="btn-sm btn btn-outline-secondary") }}
</div>

app/templates/posts/_form_posts.html
{% from "_form_field.html" import form_field %}
{{form_field(form.title, class="form-control")}}
<label for="content-post">Contenido</label>
<div class="form-group" id="content-post">
	{{ form.pagedown(only_input=True, class='form-control h text-font-size') }}
	<div class="border p-3 mt-3">
		{{ form.pagedown(only_preview=True, class='form-control text-font-size') }}
	</div>
</div>
{{ form_field(form.upload, class="form-control-sm") }}

app/templates/posts/new.html
{% extends 'index.html' %}
{% block contenido %}
{% if current_user.is_authenticated and current_user.can(Permission.WRITE_POST) %}
<div class="row">
	<div class="col-md-8 my-auto">
		<div class="modal-body">
			<form method="post" enctype="multipart/form-data">
				{{ form.hidden_tag() }}
				{% include 'posts/_form_posts.html' %}
				<div class="modal-footer">
					{{ form.submit(class="btn btn-outline-success") }}
				</div>
			</form>
		</div>
	</div>
</div>
{% endif %}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/posts/show.html
{% extends 'base.html' %}
{% from "_form_field.html" import form_field %}
{% block contenido %}
  <div class="row">
    <div class="col-md-8">
      <fieldset class="post-show">
        {% if post.author.upload %}
          <img class="image-account-post" src="{{ post.author.upload_path }}" alt="Foto de mi perfil">
        {% endif %}
        <span class="post-author-username text-info"><b>Autor: </b>{{ post.author.username}}</span>
        <p class="text-muted mt-1"><b>Publicado: </b>{{post.date_register.strftime('%d ,%B %Y')}}</p>
        <legend>
          <h3 class="text-primary">{{post.title}}</h3>
          {% if current_user == post.author %}
            <button type="button" class="btn-sm btn btn-outline-success" data-toggle="modal" data-target="#updatePost" data-whatever="@getbootstrap">Actualizar mi Post</button>
            <button type="button" class="btn-sm btn btn-danger" data-toggle="modal" data-target="#postdelete">Eliminar</button>
          {% endif %}
        </legend>
        {% if post.upload %}
          <img class="post-img" src="{{ post.upload_path }}" alt="Imagen del Post">
        {% else %}
        {% endif %}
        <div class="post-content">
          <p class="text-break">{{ post.content_html | safe }}</p>
        </div>
      </fieldset>
    </div>
    <div class="col-md-4">
      {% if current_user.is_authenticated and current_user.can(Permission.COMMENT) %}
        <div class="ml-4">
          <button class="btn-sm btn btn-info" data-toggle="collapse" data-target="#collapseComment">Comentar este Post</button>
          <div class="collapse" id="collapseComment">
            <form class="my-1" action="{{ url_for('posts.comment', slug = post.slug)}}" method="POST">
              {{ c_form.hidden_tag() }}
              {% include "posts/_form_comment.html" %}
            </form>
          </div>
        </div>
      {% endif %}
      <div class="vl"></div>
      {% include "posts/_comments.html" %}
    </div>
  </div>
  {% if current_user == post.author %}
    <!-- Modal -->
    <div class="modal fade" id="postdelete" tabindex="-1" role="dialog" aria-labelledby="postdeleteLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h4>Estas Seguro de quere eliminar tu Post - <span class="text-info">{{ post.title }}</span></h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            <form action="{{ url_for('posts.post_delete',slug = post.slug) }}" method="post">
              {{ form.hidden_tag() }}
              <input type="submit" class="btn btn-danger" value="Si, Eliminar">
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Actualizar Post -->
    <div class="modal fade bd-example-modal-lg" id="updatePost" tabindex="-1" role="dialog" aria-labelledby="updatePostLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Actualiza tu Post</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form method="POST" action="{{ url_for('posts.post', slug = post.slug) }}"  enctype="multipart/form-data">
              {{ form.hidden_tag() }}
              {% include 'posts/_form_posts.html' %}
              <div class="modal-footer">
                {{ form.submit(class="btn btn-outline-success", value = "Actualizar") }}
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
  {{ pagedown.include_pagedown() }}
{% endblock contenido %}